### ISSUE TITLE
Fix responsiveness on first item in country specific news card (see screenshot)

### ISSUE THREAD

**Issue by jkaplanis** [jkaplanis/covid19-tracker#110]

**Comment by jkaplanis** [comment]
![image](https://user-images.githubusercontent.com/60801135/77718963-6863a500-6fa1-11ea-9f4f-c77be9632d85.png)

**Comment by jkaplanis** [comment]
Also, doesn't seem to scroll to the last article. 
![image](https://user-images.githubusercontent.com/60801135/77719126-bd9fb680-6fa1-11ea-93cd-b8b7325d88b3.png)

**Comment by tylorkolbeck** [comment]
I am not having that news article overflowing issue in mine.I wonder if it was a one off with that news source.  But I am having the footer issue.
